# Generated by Django 4.1 on 2023-12-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choosecoursemsg',
            fields=[
                ('courseid', models.OneToOneField(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.course')),
            ],
            options={
                'db_table': 'ChooseCourseMsg',
                'managed': False,
            },
        ),
    ]
