# Generated by Django 4.2.8 on 2023-12-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choosecoursemsg',
            unique_together=set(),
        ),
    ]
