# Generated by Django 4.1 on 2023-12-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_course_signinmsg_teacher_student_signmsg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinmsg',
            name='begintime',
            field=models.DateTimeField(blank=True, db_column='BeginTime', null=True),
        ),
    ]
