# Generated by Django 4.2.8 on 2023-12-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_choosecoursemsg_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosecoursemsg',
            name='courseid',
            field=models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='common.course'),
        ),
    ]
