# Generated by Django 4.1 on 2023-11-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_student_user_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True},
        ),
    ]
