# Generated by Django 4.1 on 2023-12-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_signinmsg_begintime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signmsg',
            name='studentid',
        ),
    ]
