# Generated by Django 4.1 on 2023-12-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_signmsg_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='signmsg',
            name='studentid',
            field=models.OneToOneField(db_column='StudentID', default=123456, on_delete=django.db.models.deletion.DO_NOTHING, to='common.student'),
            preserve_default=False,
        ),
    ]
