# Generated by Django 4.1 on 2023-11-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_course_options'),
    ]

    operations = [

    ]
