# Generated by Django 4.1 on 2023-12-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_signmsg_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signmsg',
            name='studentid',
        ),
    ]
