# Generated by Django 4.1 on 2023-11-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_course_coursename_course_teachernum'),
    ]

    operations = [

    ]
