# Generated by Django 4.1 on 2023-12-08 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_signmsg_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signmsg',
            name='studentid',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.DO_NOTHING, to='common.student'),
        ),
    ]
