# Generated by Django 4.1 on 2023-11-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_course_coursename_course_teachernum'),
    ]

    operations = [
    ]
