# Generated by Django 4.1 on 2023-11-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_course_coursename_course_teachernum'),
    ]

    operations = [

    ]
